// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_zanmang_loopy_profile_2_png);    // assets/Zanmang_Loopy_profile_2.png
LV_IMG_DECLARE(ui_img_271117282);    // assets/bluetooth-disconnected_32x32.png
LV_IMG_DECLARE(ui_img_battery_32x32_png);    // assets/battery_32x32.png
LV_IMG_DECLARE(ui_img_shoe_32x32_png);    // assets/shoe_32x32.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
