// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_monsterbg;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_steps;
extern lv_obj_t * ui_batPercent;
extern lv_obj_t * ui_footIcon;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_dayName;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Timer;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_Bar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

